# Use root/example as user/password credentials
version: '3.1'

services:
  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/videos:/videos
      - ./backend/thumbnails:/thumbnails
  frontend:
    depends_on:
      - backend
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: backend
      REACT_APP_RESOURCE_URL: backend
      REACT_APP_WS_URL: backend
  nginx:
    depends_on:
      - frontend
      - backend
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
